### ISSUE TITLE
[cbridge] Add message when Generator is missing

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/generator-bridge#15]
**The Problem To Be Solved**

When a generator is not installed, output a message using the `download-url` that is in `global.generator.yml`.

```yml
generator:
  - id: CubeMX
    description: Global Registered Generator
    download-url: https://www.st.com/en/development-tools/stm32cubemx.html#st-get-software
    run: ../bin/cbridge
    path: $SolutionDir()$/STM32CubeMX/$TargetType$
```

**Suggest A Solution**

Output an error, for example with this format:
```
error cbridge: generator `<id>` missing. Install from `<download-url>`
```

Example:
```
error cbridge: generator `CubeMX` missing. Install from `https://www.st.com/en/development-tools/stm32cubemx.html#st-get-software`
```
