### ISSUE TITLE
Keil multiply definitions when multi-target

### ISSUE THREAD

**Issue by minicarpet** [Open-CMSIS-Pack/generator-bridge#95]
**Describe the bug**
Using Keil uVision with project having 2 multi targets, we need to generate CubeMX file for each target, then all files is used from project which occurs to multiply definitions of all generated functions.
Maybe this is missunderstood how to use it.

**To Reproduce**

1. Starts Keil
2. Create a project
3. Add an other target
![image](https://github.com/user-attachments/assets/21db98bd-675a-426f-b668-d295300cff6d)
5. Generate for each target CubeMX files as asked
![image](https://github.com/user-attachments/assets/5d0d9e31-636d-49f8-a0d1-f6b3f3122cbc)
![image](https://github.com/user-attachments/assets/e89482c4-4763-4430-b963-67951ac4b743)
6. Compile
![image](https://github.com/user-attachments/assets/63209e13-bc04-438a-8004-635d01c6cea2)

**Expected behavior**

- All targets should use the same generated files OR
- Include only generated files for the target (exclude all others)

**Environment (please complete the following information):**

- keil uVision: 5.41
- STM32CubeMX 6.12.1
- cbridge: generator-bridge version 0.9.11 (C) 2023-2024 Arm Ltd.
- device: STM32L4P5CEUx, packs: ARM::CMSIS 6.1.0 ; Keil::STM32L4xx_DFP 3.0.0
- OS: windows

**Additional context**
I used as workaround:
- modify path of CubeMX generator into `C:\Keil_v5\ARM\cmsis-toolbox\etc\global.generator.yml`:
```
generator:
  - id: CubeMX
    description: Global Registered Generator
    download-url: https://www.st.com/en/development-tools/stm32cubemx.html#st-get-software
    run: ../bin/cbridge
    path: $SolutionDir()$/STM32CubeMX
```
- Adapt cbridge go code (see [my commit](https://github.com/minicarpet/generator-bridge/commit/c99fa45723a94673267a44b544fe9fdfabcf100d) from forked repository)
**Note**: The modification of `internal/stm32CubeMX/mxDevice.go` is done because I use peripheral generation as pair

**OR**

What I can do manually is to not include generated files dependings on target:
![image](https://github.com/user-attachments/assets/6e85dca4-b106-47d3-970e-6fd6db6ad2ba)
